# Generated by Django 5.2.5 on 2025-08-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="default_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
